backend:
  name: github
  repo: leandromds/leandromsilva.com.br
  branch: master
locale: pt
media_folder: static/assets/images/uploads
public_folder: /assets/images/uploads
media_folder_relative: true
publish_mode: editorial_workflow

collections:
  - label: Posts - Versão em Inglês # Used in the UI
    name: english_posts # Used in routes, e.g., /admin/collections/blog
    folder: content/posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: language, value: en}
    fields: # The fields for each document, usually in front matter
      - { label: Idioma, name: language, widget: select, options: ["en", "pt-br"]}
      - { label: Layout, name: layout, widget: hidden, default: post }
      - {
          label: Data,
          name: date,
          widget: datetime,
          format: YYYY-MM-DD hh:mm:ss,
        }
      - { label: Capa, name: image, widget: image }
      - { label: Titulo, name: title, widget: string }
      - { label: Descrição, name: description, widget: string }
      - { label: Tags, name: tags, widget: list, default: [''] }
      - { label: Conteúdo, name: body, widget: markdown }
  - label: Posts - Versões em Português # Used in the UI
    name: brazilian_portuguese_posts # Used in routes, e.g., /admin/collections/blog
    folder: content/posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {field: language, value: pt-br}
    fields: # The fields for each document, usually in front matter
      - { label: Idioma, name: language, widget: select, options: ["en", "pt-br"]}
      - { label: Layout, name: layout, widget: hidden, default: post }
      - {
          label: Data,
          name: date,
          widget: datetime,
          format: YYYY-MM-DD hh:mm:ss,
        }
      - { label: Capa, name: image, widget: image }
      - { label: Titulo, name: title, widget: string }
      - { label: Descrição, name: description, widget: string }
      - { label: Tags, name: tags, widget: list, default: [''] }
      - { label: Conteúdo, name: body, widget: markdown }
